# Generated by Django 2.1.5 on 2020-07-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('image_1', models.ImageField(blank=True, height_field=120, upload_to='media', width_field=120)),
                ('image_2', models.ImageField(blank=True, height_field=120, upload_to='media', width_field=120)),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
    ]
